In [1]:
import tensorflow as tf

In [2]:
p = tf.placeholder('float', None)

In [3]:
type(p)

tensorflow.python.framework.ops.Tensor

In [4]:
print(p)

Tensor("Placeholder:0", dtype=float32)


In [5]:
operation = p + 2

In [6]:
print(operation)

Tensor("add:0", dtype=float32)


In [13]:
with tf.Session() as sess:
    #print(sess.run(operation))
    result = sess.run(operation, feed_dict = {p:[1,2,3]})
    print(result)

[3. 4. 5.]


In [15]:
p2 = tf.placeholder('float', [None, 5])
operation2 = p2 * 5

In [17]:
with tf.Session() as sess:
    dados = [[1,2,3,4,5], [6,7,8,9,10]]
    result = sess.run(operation, feed_dict = {p:dados})
    print(result)

[[ 3.  4.  5.  6.  7.]
 [ 8.  9. 10. 11. 12.]]
